# netlify.toml - CORREGIDO para SEPAM

[build]
  publish = "build"

# Headers para Service Worker
[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Service-Worker-Allowed = "/"

# Headers para Manifest
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=0"

# SPA Redirect - SOLO para rutas que no existen
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200